### PR TITLE
Enable generation for DATE time, enable millis for TIMESTAMP

### PR DESCRIPTION
**Pull request by snuyanzin**
The idea is to override java-faker's `date` method to generate `java.sql.Timestamp` instead of `Date`. It prints millis in `toString`.
All the methods are same: just generation of `Timestamp` objects based on `Date`

### CODE REVIEW

**Comment by knaufk** [comment]
Thank @snuyanzin for the PR. It makes sense to support more types. Can you also update the README.md and add newly supported types to the tests via https://github.com/knaufk/flink-faker/blob/master/src/test/java/com/github/knaufk/flink/faker/TestUtils.java#L8.

**Comment by snuyanzin** [comment]
Thanks for your feedback.
A added test for `DATE` to TestUtils and added info about `DATE` to README.md
Also added some examples for `TIMESTAMP` and `DATE` 
and added pipes `|` on either end of the row for compatibility as it is mentioned at https://www.markdownguide.org/extended-syntax/#tables

**Comment by knaufk** [comment]
Thanks. I realized that Travis was actually not executing all the tests and fixed this on `master`. Could you rebase and fix the test failures (along the lines of https://github.com/knaufk/flink-faker/commit/559b942d09e6855a513d70995dd4bb6b63542031)?

**Comment by snuyanzin** [comment]
Thanks  for fixing tests.
I've rebased and included your changes.

**Comment by knaufk** [comment]
Thanks for addressing the tests and rebasing. Merging now.

**Pull request merged**
